services:
  ragpy-app:
    build: .
    container_name: rag_container
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./docs:/app/docs    
      - ./data:/app/data    
    restart: always